# Generated by Django 4.1.5 on 2023-02-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0013_remove_emprestimo_tempo_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
    ]
